### ISSUE TITLE
TADP - not caching transaction configuration

### ISSUE THREAD

**Issue by Lenbkr** [frmscoe/General-Issues#240] opened 2023-08-23 07:53 UTC
We are calling the database .getTransactionConfig() method each time instead of caching it via Node Cache.

- Add Node Cache
- Add Cache TTL

**Comment by johanfol** [comment] 2023-08-28 07:58
Duplicate of https://github.com/frmscoe/General-Issues/issues/245

**Closed by johanfol** 2023-08-28 07:58 UTC
