### ISSUE TITLE
Create more granular roles and responsibilities for Tazama contributors

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/General-Issues#393] opened 2024-04-09 16:45 UTC
Proposed:
- Members - read access to all repositories
- Contributors - read/write access to all repositories
- Committers - merge authority
- Owners - all access

**Comment by Sandy-at-Tazama** [comment] 2024-05-21 06:21
Duplicate of Tazama-project #3

**Closed by Sandy-at-Tazama** 2024-05-21 06:21 UTC
